# docker-compose.dev.yml

services:
  mysql:
    ports:
      - "3307:3306"

  mongo:
    ports:
      - "27018:27017"

  redis:
    ports:
      - "6380:6379"

  kafka1:
    ports:
      - "9092:9092"

  kafka-ui:
    ports:
      - "8081:8080"
