services:
  mysql:
    image: mysql:8.0
    container_name: quotation_mysql
    environment:
      MYSQL_ROOT_PASSWORD: shiyuq
      MYSQL_DATABASE: know_your_quotation
    ports:
      - "3307:3306"
    volumes:
      - ./db/mysql:/var/lib/mysql
    networks:
      - app_net

  mongo:
    image: mongo:6
    container_name: quotation_mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: superadmin
      MONGO_INITDB_ROOT_PASSWORD: shiyuq
    ports:
      - "27018:27017"
    volumes:
      - ./db/mongo:/data/db
    networks:
      - app_net

  redis:
    image: redis:7
    container_name: quotation_redis
    ports:
      - "6380:6379"
    volumes:
      - ./db/redis:/data
    networks:
      - app_net

networks:
  app_net:
    driver: bridge
