# docker-compose.yml
volumes:
  clickhouse_data: # 声明命名卷

services:
  mysql:
    image: mysql:8.0
    container_name: quotation_mysql
    environment:
      MYSQL_ROOT_PASSWORD: shiyuq
      MYSQL_DATABASE: know_your_quotation
    volumes:
      - ./db/mysql:/var/lib/mysql
    networks:
      - app_net
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  mongo:
    image: mongo:6
    container_name: quotation_mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: superadmin
      MONGO_INITDB_ROOT_PASSWORD: shiyuq
    volumes:
      - ./db/mongo:/data/db
    networks:
      - app_net
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 10s
      timeout: 10s
      retries: 5

  redis:
    image: redis:7
    container_name: quotation_redis
    volumes:
      - ./db/redis:/data
    networks:
      - app_net
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  clickhouse:
    image: clickhouse/clickhouse-server:25.12
    container_name: quotation_clickhouse
    hostname: quotation_clickhouse
    ports:
      - "8123:8123" # HTTP 接口（常用客户端、JDBC、DBeaver 等）
      - "9000:9000" # Native TCP 接口（clickhouse-client 用）
      - "9009:9009" # HTTP 接口可选端口
    volumes:
      - clickhouse_data:/var/lib/clickhouse
    environment:
      - CLICKHOUSE_DB=logs_db # 默认创建数据库
      - CLICKHOUSE_USER=admin
      - CLICKHOUSE_PASSWORD=shiyuq # 建议改成强密码
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "localhost:8123/ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - app_net

networks:
  app_net:
    driver: bridge
