services:
  mysql:
    image: mysql:8.0
    container_name: quotation_mysql
    environment:
      MYSQL_ROOT_PASSWORD: shiyuq
      MYSQL_DATABASE: know_your_quotation
    ports:
      - "3307:3306"
    volumes:
      - ./db/mysql:/var/lib/mysql
    networks:
      - app_net

  mongo:
    image: mongo:6
    container_name: quotation_mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: superadmin
      MONGO_INITDB_ROOT_PASSWORD: shiyuq
    ports:
      - "27018:27017"
    volumes:
      - ./db/mongo:/data/db
    networks:
      - app_net

  redis:
    image: redis:7
    container_name: quotation_redis
    ports:
      - "6380:6379"
    volumes:
      - ./db/redis:/data
    networks:
      - app_net

  backend:
    build:
      context: ./backend-end
    container_name: quotation_backend
    restart: always
    env_file:
      - ./backend-end/.env.production
    environment:
      NODE_ENV: production
    depends_on:
      - mysql
      - mongo
      - redis
    ports:
      - "3000:3000"
    networks:
      - app_net

  front:
    build:
      context: ./front-end
    container_name: quotation_front
    restart: always
    ports:
      - "8080:80"
    depends_on:
      - backend
    networks:
      - app_net
networks:
  app_net:
    driver: bridge
