global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'nest-backend'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['quotation_backend:3000']  # backend 容器名:端口
